[tool.black]
line_length = 79
target_version = ["py37"]

[tool.coverage.run]
branch = true
source = ["aiopvpc"]

[tool.coverage.paths]
source = ["aiopvpc/"]

[tool.coverage.report]
fail_under = 25
skip_covered = true
show_missing = true
exclude_lines = [
    "pragma: no cover",
    "if __name__ == \"__main__\":",
    "raise NotImplementedError",
]

[tool.poetry]
name = "aiopvpc"
version = "0.1.0"
description = "PVPC Spanish Electricity prices retrieval"
authors = ["Eugenio Panadero <eugenio.panadero@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/azogue/aiopvpc"

[tool.poetry.dependencies]
python = "^3.7"
aiohttp = "^3.6"
async_timeout = "^3.0"

[tool.poetry.dev-dependencies]
pytest-sugar = "^0.9.2"
pytest = "^5.4.1"
pytest-cov = "^2.8.1"
pytest-timeout = "^1.3.4"
pytest-aiohttp = "^0.3.0"

[build-system]
requires = ["poetry>=1.0.0"]
build-backend = "poetry.masonry.api"